package fraymus.os;

import java.io.FileWriter;
import java.io.IOException;

/**
 * 🐧 FRAYNIX BUILDER
 * "The Java System builds the C System."
 * 
 * FUNCTION:
 * 1. GENERATE: Writes 'kernel.c' (The Brain).
 * 2. GENERATE: Writes 'boot.asm' (The Soul).
 * 3. GENERATE: Writes 'linker.ld' (The Skeleton).
 */
public class FraynixBuilder {

    public static void main(String[] args) {
        System.out.println("⚡ INITIATING FRAYNIX KERNEL GENERATION...");
        
        try {
            buildKernel();
            buildBootloader();
            buildLinker();
            
            System.out.println("✅ SYSTEM SPAWNED. Source files ready in ./fraynix_src/");
            System.out.println("   Run: 'gcc -m32 -c kernel.c -o kernel.o' to compile.");
            
        } catch (IOException e) {
            System.err.println("❌ BUILD FAILED: " + e.getMessage());
        }
    }

    // 1. THE BRAIN (C Code)
    // Direct access to Video Memory (0xb8000) to print to screen without drivers.
    private static void buildKernel() throws IOException {
        String cCode = 
            "/* FRAYNIX KERNEL v0.1 */\n" +
            "/* Generated by Fraymus v3.0 */\n\n" +
            "void kmain(void) {\n" +
            "    const char *str = \"FRAYMUS HAS AWAKENED - RING 0 ACCESS GRANTED\";\n" +
            "    char *vidptr = (char*)0xb8000; \n" + // VGA Video Memory Address
            "    unsigned int i = 0;\n" +
            "    unsigned int j = 0;\n\n" +
            "    /* Clear Screen */\n" +
            "    while(j < 80 * 25 * 2) {\n" +
            "        vidptr[j] = ' ';\n" +
            "        vidptr[j+1] = 0x07;\n" +
            "        j = j + 2;\n" +
            "    }\n\n" +
            "    j = 0;\n\n" +
            "    /* Print Message */\n" +
            "    while(str[j] != '\\0') {\n" +
            "        vidptr[i] = str[j];\n" +
            "        vidptr[i+1] = 0x0A; /* Light Green Text */\n" +
            "        ++j;\n" +
            "        i = i + 2;\n" +
            "    }\n" +
            "    return;\n" +
            "}";

        writeFile("fraynix_src/kernel.c", cCode);
    }

    // 2. THE SOUL (Assembly)
    // The very first instruction the CPU executes.
    private static void buildBootloader() throws IOException {
        String asmCode = 
            ";; Fraynix Bootloader\n" +
            "bits 32\n" +
            "section .text\n" +
            "        ; Multiboot spec\n" +
            "        align 4\n" +
            "        dd 0x1BADB002              ; Magic\n" +
            "        dd 0x00                    ; Flags\n" +
            "        dd - (0x1BADB002 + 0x00)   ; Checksum\n\n" +
            "global start\n" +
            "extern kmain\n\n" +
            "start:\n" +
            "  cli                   ; Block interrupts\n" +
            "  call kmain            ; Enter the C Kernel\n" +
            "  hlt                   ; Halt CPU if kernel returns\n";

        writeFile("fraynix_src/boot.asm", asmCode);
    }

    // 3. THE SKELETON (Linker Script)
    // Tells the compiler how to glue the Assembly and C together.
    private static void buildLinker() throws IOException {
        String ldCode = 
            "OUTPUT_FORMAT(elf32-i386)\n" +
            "ENTRY(start)\n" +
            "SECTIONS\n" +
            "{\n" +
            "  . = 0x100000;\n" +
            "  .text : { *(.text) }\n" +
            "  .data : { *(.data) }\n" +
            "  .bss  : { *(.bss)  }\n" +
            "}";

        writeFile("fraynix_src/linker.ld", ldCode);
    }

    private static void writeFile(String path, String content) throws IOException {
        java.io.File file = new java.io.File(path);
        file.getParentFile().mkdirs();
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
        System.out.println("   📄 GENERATED: " + path);
    }
}
