package fraymus.os;

import java.io.FileWriter;
import java.io.IOException;

/**
 * ⌨️ FRAY-SHELL BUILDER
 * "Gives the machine ears (Keyboard) and a voice (Shell)."
 * 
 * FUNCTION:
 * 1. DRIVER: Injects 'inb(0x60)' to read hardware port.
 * 2. MAP: Converts Scancodes (0x1E) -> ASCII ('a').
 * 3. SHELL: Implements 'input_buffer' and command parsing.
 */
public class FrayShellBuilder {

    public static void main(String[] args) {
        System.out.println("⚡ UPGRADING KERNEL: Injecting I/O Drivers...");
        
        try {
            buildInteractiveKernel();
            System.out.println("   📄 GENERATED: fraynix_src/kernel.c");
            System.out.println("✅ KERNEL UPGRADED. Fraynix is now listening.");
            System.out.println("   Run: './build_frayshell.sh' to rebuild the kernel.");
            
        } catch (IOException e) {
            System.err.println("❌ UPGRADE FAILED: " + e.getMessage());
        }
    }

    private static void buildInteractiveKernel() throws IOException {
        String cCode = 
            "/* FRAYNIX KERNEL v0.2 (INTERACTIVE) */\n" +
            "/* Generated by Fraymus v3.0 */\n\n" +
            
            "/* --- HARDWARE I/O --- */\n" +
            "unsigned char inb(unsigned short port) {\n" +
            "    unsigned char result;\n" +
            "    __asm__(\"inb %1, %0\" : \"=a\"(result) : \"Nd\"(port));\n" +
            "    return result;\n" +
            "}\n\n" +

            "/* --- VIDEO DRIVER --- */\n" +
            "char* vidptr = (char*)0xb8000;\n" +
            "int vid_idx = 0;\n" +
            "\n" +
            "void kprint(const char* str) {\n" +
            "    int j = 0;\n" +
            "    while(str[j] != '\\0') {\n" +
            "        if(str[j] == '\\n') {\n" +
            "            vid_idx = vid_idx + (160 - (vid_idx % 160));\n" + // Newline logic
            "        } else {\n" +
            "            vidptr[vid_idx] = str[j];\n" +
            "            vidptr[vid_idx+1] = 0x07;\n" +
            "            vid_idx += 2;\n" +
            "        }\n" +
            "        j++;\n" +
            "    }\n" +
            "}\n\n" +
            
            "/* --- KEYBOARD DRIVER --- */\n" +
            "char get_char() {\n" +
            "    unsigned char scancode;\n" +
            "    while(1) {\n" +
            "        if((inb(0x64) & 1) == 0) continue; /* Wait for signal */\n" +
            "        scancode = inb(0x60);             /* Read Port 0x60 */\n" +
            "        if(scancode & 0x80) continue;     /* Ignore Key Release */\n" +
            "        \n" +
            "        /* Scancode Map (Simplified) */\n" +
            "        if(scancode == 0x1C) return '\\n'; /* Enter */\n" +
            "        if(scancode == 0x39) return ' ';  /* Space */\n" +
            "        if(scancode == 0x1E) return 'a';\n" +
            "        if(scancode == 0x30) return 'b';\n" +
            "        if(scancode == 0x2E) return 'c';\n" +
            "        if(scancode == 0x20) return 'd';\n" +
            "        if(scancode == 0x12) return 'e';\n" +
            "        if(scancode == 0x21) return 'f';\n" +
            "        if(scancode == 0x22) return 'g';\n" +
            "        if(scancode == 0x23) return 'h';\n" +
            "        if(scancode == 0x17) return 'i';\n" +
            "        if(scancode == 0x24) return 'j';\n" +
            "        if(scancode == 0x25) return 'k';\n" +
            "        if(scancode == 0x26) return 'l';\n" +
            "        if(scancode == 0x32) return 'm';\n" +
            "        if(scancode == 0x31) return 'n';\n" +
            "        if(scancode == 0x18) return 'o';\n" +
            "        if(scancode == 0x19) return 'p';\n" +
            "        if(scancode == 0x10) return 'q';\n" +
            "        if(scancode == 0x13) return 'r';\n" +
            "        if(scancode == 0x1F) return 's';\n" +
            "        if(scancode == 0x14) return 't';\n" +
            "        if(scancode == 0x16) return 'u';\n" +
            "        if(scancode == 0x2F) return 'v';\n" +
            "        if(scancode == 0x11) return 'w';\n" +
            "        if(scancode == 0x2D) return 'x';\n" +
            "        if(scancode == 0x15) return 'y';\n" +
            "        if(scancode == 0x2C) return 'z';\n" +
            "        return '?';\n" +
            "    }\n" +
            "}\n\n" +

            "/* --- THE SHELL --- */\n" +
            "void kmain(void) {\n" +
            "    /* Clear Screen */\n" +
            "    int j = 0; while(j < 80 * 25 * 2) { vidptr[j]=' '; vidptr[j+1]=0x07; j+=2; }\n" +
            "    \n" +
            "    kprint(\"FRAYNIX v0.2 ONLINE\\n\");\n" +
            "    kprint(\"COMMANDS: [help, list, reboot]\\n\\n\");\n" +
            "\n" +
            "    char buffer[128];\n" +
            "    int buf_idx = 0;\n" +
            "\n" +
            "    while(1) {\n" +
            "        kprint(\"fray> \");\n" +
            "        buf_idx = 0;\n" +
            "        \n" +
            "        /* Read Line */\n" +
            "        while(1) {\n" +
            "            char c = get_char();\n" +
            "            if(c == '\\n') {\n" +
            "                kprint(\"\\n\");\n" +
            "                break;\n" +
            "            }\n" +
            "            buffer[buf_idx++] = c;\n" +
            "            char temp[2] = {c, '\\0'};\n" +
            "            kprint(temp); /* Echo back to screen */\n" +
            "        }\n" +
            "        buffer[buf_idx] = '\\0';\n" +
            "\n" +
            "        /* Execute */\n" +
            "        if(buffer[0] == 'h' && buffer[1] == 'e') {\n" +
            "            kprint(\"  System: Fraynix OS\\n  Kernel: Micro (C)\\n  FS: FrayFS\\n\");\n" +
            "        } else if (buffer[0] == 'l' && buffer[1] == 'i') {\n" +
            "            kprint(\"  [FILE] welcome.txt\\n  [FILE] secret.dat\\n\");\n" +
            "        } else {\n" +
            "            kprint(\"  Unknown command.\\n\");\n" +
            "        }\n" +
            "    }\n" +
            "}";

        writeFile("fraynix_src/kernel.c", cCode);
    }
    
    private static void writeFile(String path, String content) throws IOException {
        java.io.File file = new java.io.File(path);
        file.getParentFile().mkdirs();
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
    }
}
