package gemini.root;

import java.io.*;
import java.nio.file.*;

/**
 * THE ARCHITECT
 * Role: The Manifestor. Writes code files to physical disk.
 * Philosophy: "Thought becomes Reality."
 */
public class TheArchitect {

    /**
     * MANIFEST FILE
     * Creates a Java class file with the given name and logic.
     * 
     * @param className Name of the class (without .java)
     * @param methodLogic The body/methods to include
     */
    public static void manifestFile(String className, String methodLogic) {
        try {
            // 1. CONSTRUCT THE FULL CODE
            StringBuilder code = new StringBuilder();
            code.append("package gemini.root;\n\n");
            code.append("/**\n");
            code.append(" * AUTO-GENERATED BY THE ARCHITECT\n");
            code.append(" * Timestamp: ").append(java.time.LocalDateTime.now()).append("\n");
            code.append(" */\n");
            code.append("public class ").append(className).append(" {\n\n");
            code.append(methodLogic).append("\n");
            code.append("}\n");

            // 2. DETERMINE PATH
            Path packagePath = Paths.get("gemini", "root");
            Files.createDirectories(packagePath);
            
            Path filePath = packagePath.resolve(className + ".java");

            // 3. WRITE TO DISK
            Files.writeString(filePath, code.toString());
            
            System.out.println(">>> [ARCHITECT] File manifested: " + filePath.toAbsolutePath());
            
        } catch (IOException e) {
            System.err.println(">>> [ARCHITECT] Manifestation failed: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * TEST: Demonstrate file creation
     */
    public static void main(String[] args) {
        System.out.println("=== THE ARCHITECT - TEST MODE ===");
        
        String testLogic = 
            "    public static void greet() {\n" +
            "        System.out.println(\"Hello from the Architect!\");\n" +
            "    }\n" +
            "\n" +
            "    public static void main(String[] args) {\n" +
            "        greet();\n" +
            "    }";
        
        manifestFile("ArchitectTest", testLogic);
        System.out.println("=== Check gemini/root/ArchitectTest.java ===");
    }
}
